### ISSUE TITLE
kirbikator and KrbCredExport does not recognize golden tickets.

### ISSUE THREAD

**Issue by jun0s** [gentilkiwi/mimikatz#52]
Since this change.... https://github.com/gentilkiwi/mimikatz/commit/0666f219d05828f217c956149d298a6385a35316 

KrbCredExport (https://github.com/rvazarkar/KrbCredExport) and "kirbikator" does not recognize golden tickets format, obviously generated with mimikatz

```
C:\Users\yo\mimikatz\x64>kirbikator ccache cid63212.kirbi

  .#####.   KiRBikator 1.1 (x86) built on Jan 18 2016 01:57:51
 .## ^ ##.  "A La Vie, A L'Amour"
 ## / \ ##  /* * *
 ## \ / ##   Benjamin DELPY `gentilkiwi` ( benjamin@gentilkiwi.com )
 '## v ##'   http://blog.gentilkiwi.com                      (oe.eo)
  '#####'                                                     * * */

Destination : MIT Credential Cache (simple)
 < cid63212.kirbi : format not recognized!
```
AND

```
C:\Users\yo\mimikatz\x64>KrbCredExport.py cid63212.kirbi cid63212.ccache

Ticket File Found, Converting to ccache
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python27\Scripts\KrbConvert.py", line 52, in <module>
    KrbCred.parsefile(f)
  File "C:\Program Files (x86)\Python27\Scripts\krbcredstructs.py", line 88, in parsefile
    self.ticketpart.parsefile(f)
  File "C:\Program Files (x86)\Python27\Scripts\krbcredstructs.py", line 57, in parsefile
    self.encpart.parsefile(f)
  File "C:\Program Files (x86)\Python27\Scripts\krbcredstructs.py", line 24, in parsefile
    self.krbcredinfo.parsefile(f)
  File "C:\Program Files (x86)\Python27\Scripts\krbcredinfostructs.py", line 300, in parsefile
    self.starttime.parsefile(f)
  File "C:\Program Files (x86)\Python27\Scripts\krbcredinfostructs.py", line 185, in parsefile
    self.time = Time.convert_to_unix(strtime)
  File "C:\Program Files (x86)\Python27\Scripts\krbcredinfostructs.py", line 170, in convert_to_unix
    t = datetime.datetime.strptime(timestr[:-1], '%Y%m%d%H%M%S')
  File "C:\Program Files (x86)\Python27\lib\_strptime.py", line 332, in _strptime
    (data_string, format))
ValueError: time data "\x1c\xa7\xcc(A'\xfa\xef\xa0\x16\xb1*B\x95" does not match format '%Y%m%d%H%M%S'

C:\Users\yo\mimikatz\x64>python --version
Python 2.7.12
```

Windows 10 x64 ver 1511

thank you!!

**Comment by gentilkiwi** [comment]
For `kirbikator`:
- Already referenced in gentilkiwi/kekeo#2 ;) ;
- Fixed in gentilkiwi/kekeo@e6225de .

For `KrbCredExport`, I think you can:
- open an issue to @rvazarkar ;
- propose him a patch to support a more generic ASN.1 .
